CREATE DATABASE QL_TRUONGDAIHOC
Use QL_TRUONGDAIHOC

CREATE TABLE KHOA
(
	MAKHOA CHAR(4) PRIMARY KEY,
	TENKHOA NVARCHAR(30) NOT NULL,
	MATK CHAR(8) NOT NULL,
	MOTA NVARCHAR(40)
)

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(8) PRIMARY KEY,
	TENGV NVARCHAR(20) NOT NULL,
	MAKHOA CHAR(4) FOREIGN KEY REFERENCES KHOA(MAKHOA),
	HOCHAM NVARCHAR(20),
	HOCVI NVARCHAR(20) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	USERNAME CHAR(8) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	MOTA NVARCHAR(40)
)

CREATE TABLE LOPSINHHOAT
(
	MALOP CHAR(4) PRIMARY KEY,
	TENLOP NVARCHAR(30) NOT NULL,
	MAKHOA CHAR(4) FOREIGN KEY REFERENCES KHOA(MAKHOA),
	MAGV CHAR(8) FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	MOTA NVARCHAR(40)
)

CREATE TABLE SINHVIEN
(
	MSSV CHAR(8) PRIMARY KEY,
	TENSV NVARCHAR(20) NOT NULL,
	MALOP CHAR(4) FOREIGN KEY REFERENCES LOPSINHHOAT(MALOP),
	EMAIL VARCHAR(40) NOT NULL,
	SDT VARCHAR(10),
	USERNAME CHAR(8) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	MOTA NVARCHAR(40)
)

CREATE TABLE MONHOC
(
	MAMH CHAR(5) PRIMARY KEY,
	TENMH NVARCHAR(20) NOT NULL,
	MAKHOA CHAR(4) FOREIGN KEY REFERENCES KHOA(MAKHOA),
	MOTA NVARCHAR(40)
)

CREATE TABLE LOPHOC
(
	MALOPHOC CHAR(11) PRIMARY KEY,
	MAMON CHAR(5) FOREIGN KEY REFERENCES MONHOC(MAMH),
	MAGV CHAR(8) FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	HOCKY SMALLINT NOT NULL,
	NAMHOC SMALLDATETIME NOT NULL,
	MOTA NVARCHAR(40)
)

CREATE TABLE BANGDIEM
(
	MSSV CHAR(8) FOREIGN KEY REFERENCES SINHVIEN(MSSV),
	MAMH CHAR(5) FOREIGN KEY REFERENCES MONHOC(MAMH),
	DIEMQT FLOAT,
	DIEMGK FLOAT NOT NULL,
	DIEMTH FLOAT,
	DIEMCK FLOAT NOT NULL,
	DIEMTB FLOAT NOT NULL,
	TONGLO INT NOT NULL,
	HOCKY SMALLINT NOT NULL,
	NAMHOC SMALLDATETIME NOT NULL,
	PRIMARY KEY(MSSV,MAMH)
)

CREATE TABLE SINHVIEN_LOPHOC
(
	MSSV CHAR(8) FOREIGN KEY REFERENCES SINHVIEN(MSSV),
	MALOPHOC CHAR(11) FOREIGN KEY REFERENCES LOPHOC(MALOPHOC),
	KETQUA NVARCHAR(10) NOT NULL,
	PRIMARY KEY(MSSV,MALOPHOC)
)

CREATE TABLE SV_CHUANDAURA
(
	MSSV CHAR(8) FOREIGN KEY REFERENCES SINHVIEN(MSSV),
	MACHUANDR CHAR(4),
	QUATRINH NVARCHAR(10) NOT NULL,
	HOCKY SMALLINT NOT NULL,
	NAMHOC SMALLDATETIME NOT NULL,
	PRIMARY KEY(MSSV,MACHUANDR)
)

CREATE TABLE SV_CHUANMH
(
	MSSV CHAR(8) FOREIGN KEY REFERENCES SINHVIEN(MSSV),
	MACHUANMH CHAR(2),
	QUATRINH NVARCHAR(10) NOT NULL,
	HOCKY SMALLINT NOT NULL,
	NAMHOC SMALLDATETIME NOT NULL,
	PRIMARY KEY(MSSV,MACHUANMH)
)

CREATE TABLE CHUANDAURA
(
	MACHUANDR CHAR(4) NOT NULL,
	MAKHOA CHAR(4) FOREIGN KEY REFERENCES KHOA(MAKHOA),
	TENCHUANDR NVARCHAR(20) NOT NULL,
	DIENGIAI NVARCHAR(40),
	PRIMARY KEY(MACHUANDR,MAKHOA)
)

CREATE TABLE CHUANMH
(
	MACHUANMH CHAR(2) NOT NULL,
	MAMH CHAR(5) FOREIGN KEY REFERENCES MONHOC(MAMH),
	TENCHUANMH NVARCHAR(20) NOT NULL,
	DIEM FLOAT NOT NULL,
	DIEMGIAI NVARCHAR(40),
	PRIMARY KEY(MACHUANMH,MAMH),
)

CREATE TABLE DAURA_MONHOC
(
	MACHUANDR_MH CHAR(3),
	MACHUANMH CHAR(2),
	PRIMARY KEY(MACHUANDR_MH,MACHUANMH)
)

CREATE TABLE QUANLY
(
	MATK CHAR(8) FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	MAGV CHAR(8) FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	PRIMARY KEY(MATK,MAGV)
)

CREATE TABLE GIANGDAY
(
	MAGV CHAR(8) FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	MALOPHOC CHAR(11) FOREIGN KEY REFERENCES LOPHOC(MALOPHOC),
	QUATRINH NVARCHAR(10),
	PRIMARY KEY(MAGV,MALOPHOC)
)

--- Tạo ràng buộc trên table Khoa ---
ALTER TABLE KHOA ADD
	CONSTRAINT FK_KH_GV FOREIGN KEY (MATK) REFERENCES GIAOVIEN(MAGV)