CREATE DATABASE QL_ChuanDauRa
Use QL_ChuanDauRa

CREATE TABLE KHOA
(
	MAKHOA CHAR(7) PRIMARY KEY,
	TENKHOA NVARCHAR(30) NOT NULL,
	MATK CHAR(8) NOT NULL,
	MOTA NVARCHAR(40)
)

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(8) PRIMARY KEY,
	TENGV NVARCHAR(30) NOT NULL,
	MAKHOA CHAR(7),
	HOCHAM NVARCHAR(20),
	HOCVI NVARCHAR(20) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	USERNAME CHAR(8) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	MOTA NVARCHAR(40)
)

CREATE TABLE LOPSINHHOAT
(
	MALOP CHAR(8) PRIMARY KEY,
	TENLOP NVARCHAR(30) NOT NULL,
	MAKHOA CHAR(7),
	MAGV CHAR(8),
	MOTA NVARCHAR(40)
)

CREATE TABLE SINHVIEN
(
	MSSV CHAR(8) PRIMARY KEY,
	TENSV NVARCHAR(30) NOT NULL,
	MALOP CHAR(8),
	EMAIL VARCHAR(40) NOT NULL,
	SDT VARCHAR(10),
	USERNAME CHAR(8) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	MOTA NVARCHAR(40)
)

CREATE TABLE MONHOC
(
	MAMH CHAR(5) PRIMARY KEY,
	TENMH NVARCHAR(20) NOT NULL,
	MAKHOA CHAR(7),
	MOTA NVARCHAR(40)
)

CREATE TABLE LOPHOC
(
	MALOPHOC CHAR(11),
	MAMH CHAR(5),
	MAGV CHAR(8),
	HOCKY SMALLINT NOT NULL,
	NAMHOC INT NOT NULL,
	MOTA NVARCHAR(40),
	PRIMARY KEY(MALOPHOC,HOCKY,NAMHOC)
)

CREATE TABLE BANGDIEM
(
	MSSV CHAR(8),
	MAMH CHAR(5),
	DIEMQT FLOAT,
	DIEMGK FLOAT NOT NULL,
	DIEMTH FLOAT,
	DIEMCK FLOAT NOT NULL,
	DIEMTB FLOAT NOT NULL,
	TONGLO INT NOT NULL,
	HOCKY SMALLINT NOT NULL,
	NAMHOC INT NOT NULL,
	PRIMARY KEY(MSSV,MAMH)
)

CREATE TABLE SINHVIEN_LOPHOC
(
	MSSV CHAR(8),
	MALOPHOC CHAR(11),
	KETQUA NVARCHAR(20) NOT NULL,
	PRIMARY KEY(MSSV,MALOPHOC)
)

CREATE TABLE SV_CHUANDAURA
(
	MSSV CHAR(8),
	MACHUANDR CHAR(6),
	QUATRINH NVARCHAR(20) NOT NULL,
	HOCKY SMALLINT NOT NULL,
	NAMHOC INT NOT NULL,
	PRIMARY KEY(MSSV,MACHUANDR)
)

CREATE TABLE SV_CHUANMH
(
	MSSV CHAR(8),
	MACHUANMH CHAR(2),
	QUATRINH NVARCHAR(20) NOT NULL,
	HOCKY SMALLINT NOT NULL,
	NAMHOC INT NOT NULL,
	PRIMARY KEY(MSSV,MACHUANMH)
)

CREATE TABLE CHUANDAURA
(
	MACHUANDR CHAR(6) NOT NULL,
	MAKHOA CHAR(7),
	TENCHUANDR NVARCHAR(20) NOT NULL,
	DIENGIAI NVARCHAR(40),
	PRIMARY KEY(MACHUANDR,MAKHOA)
)

CREATE TABLE CHUANMH
(
	MACHUANMH CHAR(2) NOT NULL,
	MAMH CHAR(5),
	TENCHUANMH NVARCHAR(20) NOT NULL,
	DIEM FLOAT NOT NULL,
	DIENGIAI NVARCHAR(40),
	PRIMARY KEY(MACHUANMH,MAMH),
)

CREATE TABLE DAURA_MONHOC
(
	MACHUANDR_MH CHAR(3),
	MACHUANMH CHAR(2),
	PRIMARY KEY(MACHUANDR_MH,MACHUANMH)
)

CREATE TABLE QUANLY
(
	MATK CHAR(8),
	MAGV CHAR(8),
	PRIMARY KEY(MATK,MAGV)
)

CREATE TABLE GIANGDAY
(
	MAGV CHAR(8),
	MALOPHOC CHAR(11),
	QUATRINH NVARCHAR(20),
	HOCKY SMALLINT NOT NULL,
	NAMHOC INT NOT NULL,
	PRIMARY KEY(MAGV,MALOPHOC)
)

--- Tạo ràng buộc trên các Table ---
ALTER TABLE KHOA ADD
	CONSTRAINT FK_KH_GV FOREIGN KEY (MATK) REFERENCES GIAOVIEN(MAGV)
	
ALTER TABLE GIAOVIEN ADD
	CONSTRAINT FK_GV_KH FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE LOPSINHHOAT ADD
	CONSTRAINT FK_LSH_KH FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
	CONSTRAINT FK_LSH_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE SINHVIEN ADD
	CONSTRAINT FK_SV_LSH FOREIGN KEY (MALOP) REFERENCES LOPSINHHOAT(MALOP)

ALTER TABLE MONHOC ADD
	CONSTRAINT FK_MH_KH FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE LOPHOC ADD
	CONSTRAINT FK_LH_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	CONSTRAINT FK_LH_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE BANGDIEM ADD
	CONSTRAINT FK_BD_SV FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
	CONSTRAINT FK_BD_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE SINHVIEN_LOPHOC ADD
	CONSTRAINT FK_SVLH_SV FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV)

ALTER TABLE SV_CHUANDAURA ADD
	CONSTRAINT FK_SVCDR_SV FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV)

ALTER TABLE SV_CHUANMH ADD
	CONSTRAINT FK_SVCMH_SV FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV)

ALTER TABLE CHUANDAURA ADD
	CONSTRAINT FK_CDR_KH FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE CHUANMH ADD
	CONSTRAINT FK_CMH_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE QUANLY ADD
	CONSTRAINT FK_QL1_GV FOREIGN KEY (MATK) REFERENCES GIAOVIEN(MAGV),
	CONSTRAINT FK_QL2_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE GIANGDAY ADD
	CONSTRAINT FK_GD_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

Set dateformat dmy
